<?php

function hwc_homepage_install() {
  features_revert_module('hwc_homepage');
  features_revert_module('osha_news');
}

/**
 * Revert homepage and news modules.
 */
function hwc_homepage_update_7001() {
  features_revert_module('hwc_homepage');
  features_revert_module('osha_news');
}

/**
 * Revert hwc homepage modules.
 */
function hwc_homepage_update_7002() {
  features_revert_module('hwc_homepage');
}
